-- list items table seeds here
INSERT INTO list_items (name, user_id, category) VALUES ('The Wire', 1, 'watch');
INSERT INTO list_items (name, user_id, category) VALUES ('Charlie and The Chocolate Factory', 1, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Calvin and Hobbes', 1, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Instant Pot', 1, 'buy');
INSERT INTO list_items (name, user_id, category) VALUES ('Broadway Sushi', 1, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('Pitch Perfect', 2, 'watch');
INSERT INTO list_items (name, user_id, category) VALUES ('War and Peace', 2, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Brave New World', 2, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Microwave', 2, 'buy');
INSERT INTO list_items (name, user_id, category) VALUES ('Chambar', 2, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('Noodle Box', 2, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('You', 3, 'watch');
INSERT INTO list_items (name, user_id, category) VALUES ('Sisterhood of The Travelling Pants', 3, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('The Illiad', 3, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Bar stool', 3, 'buy');
INSERT INTO list_items (name, user_id, category) VALUES ('Burger King', 3, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('The Naam', 3, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('The Witcher', 4, 'watch');
INSERT INTO list_items (name, user_id, category) VALUES ('Euphoria', 4, 'watch');
INSERT INTO list_items (name, user_id, category) VALUES ('Captin Underpants', 4, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Flip flops', 4, 'buy');
INSERT INTO list_items (name, user_id, category) VALUES ('Le Petit Saigon', 4, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('Fire Pizza', 4, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('Sleepless In Seattle', 5, 'watch');
INSERT INTO list_items (name, user_id, category) VALUES ('Visor hat', 5, 'buy');
INSERT INTO list_items (name, user_id, category) VALUES ('The Wretched of the Earth', 5, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('ear plugs', 5, 'buy');
INSERT INTO list_items (name, user_id, category) VALUES ('Hyperspace', 5, 'read');
INSERT INTO list_items (name, user_id, category) VALUES ('Four Bros Pizza', 5, 'eat');
INSERT INTO list_items (name, user_id, category) VALUES ('test', 1, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test2', 1, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test3', 2, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test4', 2, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test5', 3, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test6', 3, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test7', 4, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test8', 4, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test9', 5, 'uncategorize');
INSERT INTO list_items (name, user_id, category) VALUES ('test100', 5, 'uncategorize');
